// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"mypj/app/dao/internal"
)

// roleMenuDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type roleMenuDao struct {
	*internal.RoleMenuDao
}

var (
	// RoleMenu is globally public accessible object for table role_menu operations.
	RoleMenu = &roleMenuDao{
		internal.RoleMenu,
	}
)

// Fill with you ideas below.