// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"mypj/app/model/internal"
)

// AdminRole is the golang structure for table admin_role.
type AdminRole internal.AdminRole

// Fill with you ideas below.