// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"mypj/app/model/internal"
)

// Goods is the golang structure for table goods.
type Goods internal.Goods

// Fill with you ideas below.