// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"mypj/app/model/internal"
)

// Menu is the golang structure for table menu.
type Menu internal.Menu

// Fill with you ideas below.