// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"mypj/app/model/internal"
)

// RoleMenu is the golang structure for table role_menu.
type RoleMenu internal.RoleMenu

// Fill with you ideas below.