// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// Admins is the golang structure for table admins.
type Admins struct {
    AdminId    uint        `orm:"admin_id,primary" json:"admin_id"`    //   
    AdminName  string      `orm:"admin_name"       json:"admin_name"`  //   
    Password   string      `orm:"password"         json:"password"`    //   
    TrueName   string      `orm:"true_name"        json:"true_name"`   //   
    Email      string      `orm:"email"            json:"email"`       //   
    Mobile     string      `orm:"mobile"           json:"mobile"`      //   
    Status     string      `orm:"status"           json:"status"`      //   
    CreateTime *gtime.Time `orm:"create_time"      json:"create_time"` //   
    UpdateTime *gtime.Time `orm:"update_time"      json:"update_time"` //   
}