// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// Goods is the golang structure for table goods.
type Goods struct {
    Id          uint        `orm:"id,primary"   json:"id"`           //                     
    GoodsCode   string      `orm:"goods_code"   json:"goods_code"`   // 商品编号            
    GoodsName   string      `orm:"goods_name"   json:"goods_name"`   // 商品名称            
    GoodsCate   string      `orm:"goods_cate"   json:"goods_cate"`   // 商品分类            
    GoodsSource string      `orm:"goods_source" json:"goods_source"` //                     
    Status      uint        `orm:"status"       json:"status"`       // 状态 1 有效 2 无效  
    CreateTime  *gtime.Time `orm:"create_time"  json:"create_time"`  //                     
    UpdateTime  *gtime.Time `orm:"update_time"  json:"update_time"`  //                     
}