// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// Menu is the golang structure for table menu.
type Menu struct {
    MenuId     uint        `orm:"menu_id,primary" json:"menu_id"`     // 权限菜单Id                             
    MenuName   string      `orm:"menu_name"       json:"menu_name"`   //                                        
    Pid        uint        `orm:"pid"             json:"pid"`         // 上级id                                 
    MenuCode   string      `orm:"menu_code"       json:"menu_code"`   // 权限标识                               
    Url        string      `orm:"url"             json:"url"`         //                                        
    Level      uint        `orm:"level"           json:"level"`       // 层级                                   
    LeverCode  string      `orm:"lever_code"      json:"lever_code"`  // 层级标识 特征为拼接所有上级id及自身id  
    Type       uint        `orm:"type"            json:"type"`        // 类型 1 菜单 2 功能操作                 
    IsShow     uint        `orm:"is_show"         json:"is_show"`     // 是否显示 1 是 2 否                     
    Status     uint        `orm:"status"          json:"status"`      // 状态 1 有效 2 无效                     
    OrderNum   uint        `orm:"order_num"       json:"order_num"`   // 排序号  优先级越小越前                 
    DeleteFlag uint        `orm:"delete_flag"     json:"delete_flag"` // 删除标记 0 未删除 1 已删除             
    CreateTime *gtime.Time `orm:"create_time"     json:"create_time"` //                                        
    UpdateTime *gtime.Time `orm:"update_time"     json:"update_time"` //                                        
}