// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/os/gtime"
)

// Role is the golang structure for table role.
type Role struct {
    RoleId     uint        `orm:"role_id,primary" json:"role_id"`     //                     
    RoleName   string      `orm:"role_name"       json:"role_name"`   //                     
    Desc       string      `orm:"desc"            json:"desc"`        //                     
    Status     uint        `orm:"status"          json:"status"`      // 状态 1 有效 2 无效  
    CreateTime *gtime.Time `orm:"create_time"     json:"create_time"` //                     
    UpdateTime *gtime.Time `orm:"update_time"     json:"update_time"` //                     
}